# Generated by Django 3.2.8 on 2021-10-17 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('lastCheckDate', models.DateField(auto_now_add=True, null=True)),
                ('nextCheckDate', models.DateField(auto_now_add=True, null=True)),
                ('checker', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('departement', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='departement.departement')),
            ],
        ),
    ]
