# Generated by Django 3.2.8 on 2021-10-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='lastCheckDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='nextCheckDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
